name: ${PROJECT_NAME}
services:
  frontend:
    container_name: ${PROJECT_NAME}-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6009:6009
    networks:
      - g09-pf-net
networks:
  g09-pf-net:
    external: true